title: legge
tagline: Software ∩ Engineer ⇒ Automator
email: rikard@legge.se
description: >- # this means to ignore newlines until "baseurl:"
  Homepage for personal projects and other fun things
github_username: "RikardLegge"
author: Rikard Legge

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: pretty

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - .idea
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
